FROM gradle:jdk11-openj9
COPY . /home/gradle/src
RUN chmod 777 /home/gradle/src/gradlew
RUN ls -al
WORKDIR /home/gradle/src
RUN ./gradlew integrationTest --no-daemon

#
#
# FROM openjdk:14-alpine
# COPY . /dev
# WORKDIR /dev
# ENTRYPOINT ["gradlew", "integrationTest"]